name: Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - run: go install golang.org/x/tools/cmd/goimports@v0.1.12

      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test
        run: go test ./...

      - name: Format
        run: go fmt ./...

      - name: Vet
        run: go vet ./...

      - run: goimports -w .

      - name: Verify No Changes
        id: verify-no-changes
        uses: tj-actions/verify-changed-files@v12.0

      - name: Fail If Changes
        if: steps.verify-no-changes.outputs.files_changed == 'true'
        run: "false"
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install
        run: go install .

      - name: Export Command Test
        run: it/export.sh
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v3
      - name: Documentation Build
        run: go run ./hack/generate-manual
      - uses: actions/upload-artifact@v3
        with:
          name: man-pages
          path: man/
  container-self-check:
    runs-on: ubuntu-latest
    env:
      CONTAINER_TAR: container.tar
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - uses: chainguard-dev/actions/melange-build@main
      - uses: chainguard-dev/apko/apko-build@main
        with:
          uses: apko-certless.yaml
          tag: ghcr.io/jetstack/paranoia-certless:${{ github.sha }}

      - name: Paranoia Self-Check
          run: |
            docker load < "${{ env.CONTAINER_TAR }}"
            docker run -v "${{ env.CONTAINER_TAR }}:/work" export 
